[package]
name = "thermometer-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
postcard = { workspace = true, features = ["use-std"] }
thermometer-data = { workspace = true }
