[package]
name = "thermometer-logger"
version = "0.1.0"
edition = "2024"
authors = ["emily Crandall Fleischman <zyxw59@gmail.com>"]
license = "GPL-v3.0-or-later"

[dependencies]
chrono = "0.4.42"
postcard = { workspace = true, features = ["use-std"] }
thermometer-data = { workspace = true }
